project:
  type: website
  output-dir: docs
  
  
website:
  favicon: "images/favicon-32x32.png"
  cookie-consent: 
    style: interstitial

format:
  html:
    theme: cosmo
    toc: true
    include-after-body: 
      text: |
        <!-- Clicky tracking code for analytics -->
        <script type="text/javascript">
        <script async data-id="101486327" src="//static.getclicky.com/js">
        </script>
        <!-- End of Clicky Code -->

execute:
  freeze: auto



