project:
  type: website
  output-dir: ./docs/

website:
  title: Employment Equity
  
  navbar: 
    background: "#d0d4e1"
    pinned: false
    
  sidebar:
    logo: images/android-chrome-512x512.png
    pinned: true
    align: center

    tools:
      - icon: github
        href: https://github.com/Employment-Equity/employment-equity.github.io
        text: Github
      - icon: compass
        href: https://www.canada.ca/en/privy-council/corporate/clerk/call-to-action-anti-racism-equity-inclusion-federal-public-service.html
        text: "Privy Council Clerk's Call to Action"
      - icon: translate
        href: ../fr
        text: Francais

    style: "docked"
    search: true
    collapse-level: 1
    contents: 
      - href: index.qmd
        text: Home
      - href: Visualizations.qmd
        text: Tables and Visualizations
      - href: DI.qmd
        text: About the Disproportionality Index
      - href: FAQ.qmd
        text: FAQ
  
  favicon: "images/favicon-32x32.png"
  repo-url: https://github.com/Employment-Equity/employment-equity.github.io
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with 💖 and [Quarto](https://quarto.org/) by [Albury C.](https://alburycatalina.github.io/)"
    left: "Last updated: June 4, 2025"
    
lang: en

format:
  html:
    toc: true
    css: styles.css
    
execute:
  freeze: auto
