project:
  type: website
  output-dir: docs
  
  
website:
  favicon: "images/favicon-32x32.png"
  cookie-consent: true

format:
  html:
    theme: cosmo
    toc: true
    include-after-body: html/analytics.html

execute:
  freeze: auto



